// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAeZi3Ytbj8PWrWT7kLBVwvWfcoGXzbg8',
    appId: '1:971311776590:web:1f5c7f3d20aeaa2a8c141f',
    messagingSenderId: '971311776590',
    projectId: 'house-rent-64aee',
    authDomain: 'house-rent-64aee.firebaseapp.com',
    databaseURL: 'https://house-rent-64aee-default-rtdb.firebaseio.com',
    storageBucket: 'house-rent-64aee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6OYC6R9-VxH99YLdtK_HxYjxSgXy3CTM',
    appId: '1:971311776590:android:cd5c13f04f9fdab38c141f',
    messagingSenderId: '971311776590',
    projectId: 'house-rent-64aee',
    databaseURL: 'https://house-rent-64aee-default-rtdb.firebaseio.com',
    storageBucket: 'house-rent-64aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Qtv4j3J8lc0PkCc2h7fORsf9xHXaFXs',
    appId: '1:971311776590:ios:1c746e79c73620028c141f',
    messagingSenderId: '971311776590',
    projectId: 'house-rent-64aee',
    databaseURL: 'https://house-rent-64aee-default-rtdb.firebaseio.com',
    storageBucket: 'house-rent-64aee.appspot.com',
    iosBundleId: 'com.example.houseRent',
  );
}
